<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <StartupObject>TechStoreApp.LoginForm</StartupObject>
    <UseApplicationFramework>false</UseApplicationFramework>
    <MyType>WindowsForms</MyType>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
    <AssemblyTitle>TechStoreApp</AssemblyTitle>
    <Product>TechStoreApp</Product>
    <Copyright>Copyright ©  2025</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>TechStoreApp.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DefineDebug>false</DefineDebug>
    <DocumentationFile>TechStoreApp.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.7" />
	<PackageReference Include="System.Data.Odbc" Version="8.0.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
  </ItemGroup>
  <ItemGroup>
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="GUI\LoginForm.Designer.vb">
      <DependentUpon>LoginForm.vb</DependentUpon>
    </Compile>
    <Compile Update="GUI\MainForm.Designer.vb">
      <DependentUpon>MainForm.vb</DependentUpon>
    </Compile>
    <Compile Update="GUI\ProductManagementForm.Designer.vb">
      <DependentUpon>ProductManagementForm.vb</DependentUpon>
    </Compile>
    <Compile Update="GUI\RegisterForm.Designer.vb">
      <DependentUpon>RegisterForm.vb</DependentUpon>
    </Compile>
    <Compile Update="GUI\SelectSupplierForm.Designer.vb">
      <DependentUpon>SelectSupplierForm.vb</DependentUpon>
    </Compile>
    <Compile Update="GUI\ProductStatisticsForm.Designer.vb">
      <DependentUpon>ProductStatisticsForm.vb</DependentUpon>
    </Compile>
    <Compile Update="GUI\StockTransactionCreateForm.Designer.vb">
      <DependentUpon>StockTransactionCreateForm.vb</DependentUpon>
    </Compile>
    <Compile Update="GUI\StockTransactionDetailForm.Designer.vb">
      <DependentUpon>StockTransactionDetailForm.vb</DependentUpon>
    </Compile>
    <Compile Update="GUI\StockTransactionListForm.Designer.vb">
      <DependentUpon>StockTransactionListForm.vb</DependentUpon>
    </Compile>
    <Compile Update="GUI\SupplierManagementForm.Designer.vb">
      <DependentUpon>SupplierManagementForm.vb</DependentUpon>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="My Project\Settings.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
    </None>
  </ItemGroup>
</Project>